version: '3.8'
services:
  portfolio-cms-server:
    container_name: portfolio-cms-server
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - default
    volumes:
      - ./:/app
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
networks:
  default:
volumes:
  postgres_data: